import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'
import ReactQueryProvider from '@/lib/ReactQueryProvider'
import { NavigationBar } from '@/components/NavigationBar'
import { Footer } from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" >
      <body className={inter.className}>
        <main className="flex w-screen   min-h-screen flex-col items-center overflow-clip">
          <NavigationBar />
          {children}
        </main >
        <Footer />
      </body>
    </html>
  )
}
